number1 = int(input("enter the first number:"))
number2 = int(input("enter the second number:"))
print(number1, "+", number2, "=", number1+number2)
print(number1, "*", number2, "=", number1*number2)
print(number1, "/", number2, "=", number1/number2)
print(number1, "mod", number2, "=", number1%number2)
print(number1, "^", number2, "=", number1**number2)
