num1 = int(input("Input number 1: "))
num2 = int(input("Input number 2: "))
print("sum = " + str(num1+num2))
print("product = " + str(num1*num2))
print("ratio = " + str(num1/num2))
print("modulo = " + str(num1%num2))
print("exponent = " + str(num1^num2))